/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Addnewgame
         * @param {string} userToken 
         * @param {string} title 
         * @param {number} coordX 
         * @param {number} coordY 
         * @param {string} description 
         * @param {number} tag 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewGameAddNewGamePost: async (userToken: string, title: string, coordX: number, coordY: number, description: string, tag: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userToken' is not null or undefined
            assertParamExists('addNewGameAddNewGamePost', 'userToken', userToken)
            // verify required parameter 'title' is not null or undefined
            assertParamExists('addNewGameAddNewGamePost', 'title', title)
            // verify required parameter 'coordX' is not null or undefined
            assertParamExists('addNewGameAddNewGamePost', 'coordX', coordX)
            // verify required parameter 'coordY' is not null or undefined
            assertParamExists('addNewGameAddNewGamePost', 'coordY', coordY)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('addNewGameAddNewGamePost', 'description', description)
            // verify required parameter 'tag' is not null or undefined
            assertParamExists('addNewGameAddNewGamePost', 'tag', tag)
            const localVarPath = `/addNewGame`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userToken !== undefined) {
                localVarQueryParameter['userToken'] = userToken;
            }

            if (title !== undefined) {
                localVarQueryParameter['title'] = title;
            }

            if (coordX !== undefined) {
                localVarQueryParameter['coordX'] = coordX;
            }

            if (coordY !== undefined) {
                localVarQueryParameter['coordY'] = coordY;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }

            if (tag !== undefined) {
                localVarQueryParameter['tag'] = tag;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Getcities
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCitiesGetCitiesPost: async (skip?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/getCities`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Getuser
         * @param {number} idUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserUserPost: async (idUser: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idUser' is not null or undefined
            assertParamExists('getUserUserPost', 'idUser', idUser)
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (idUser !== undefined) {
                localVarQueryParameter['idUser'] = idUser;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Loginbytoken
         * @param {string} userToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logInByTokenLoginByTokenPost: async (userToken: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userToken' is not null or undefined
            assertParamExists('logInByTokenLoginByTokenPost', 'userToken', userToken)
            const localVarPath = `/loginByToken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userToken !== undefined) {
                localVarQueryParameter['userToken'] = userToken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login
         * @param {string} loginUser 
         * @param {string} passwordUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logInLoginPost: async (loginUser: string, passwordUser: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginUser' is not null or undefined
            assertParamExists('logInLoginPost', 'loginUser', loginUser)
            // verify required parameter 'passwordUser' is not null or undefined
            assertParamExists('logInLoginPost', 'passwordUser', passwordUser)
            const localVarPath = `/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (loginUser !== undefined) {
                localVarQueryParameter['loginUser'] = loginUser;
            }

            if (passwordUser !== undefined) {
                localVarQueryParameter['passwordUser'] = passwordUser;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Readmain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readMainGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searchforgameauthor
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameAuthorSearchForGameAuthorPost: async (data: string, sort?: string, skip?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('searchForGameAuthorSearchForGameAuthorPost', 'data', data)
            const localVarPath = `/searchForGameAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (data !== undefined) {
                localVarQueryParameter['data'] = data;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searchforgamedate
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameDateSearchForGameDatePost: async (data: string, sort?: string, skip?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('searchForGameDateSearchForGameDatePost', 'data', data)
            const localVarPath = `/searchForGameDate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (data !== undefined) {
                localVarQueryParameter['data'] = data;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searchforgamename
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameNameSearchForGameNamePost: async (data: string, sort?: string, skip?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('searchForGameNameSearchForGameNamePost', 'data', data)
            const localVarPath = `/searchForGameName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (data !== undefined) {
                localVarQueryParameter['data'] = data;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searchforgame
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameSearchForGameCityPost: async (data: string, sort?: string, skip?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('searchForGameSearchForGameCityPost', 'data', data)
            const localVarPath = `/searchForGameCity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (data !== undefined) {
                localVarQueryParameter['data'] = data;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searchforgametags
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameTagsSearchForGameTagsPost: async (data: string, sort?: string, skip?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'data' is not null or undefined
            assertParamExists('searchForGameTagsSearchForGameTagsPost', 'data', data)
            const localVarPath = `/searchForGameTags`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (data !== undefined) {
                localVarQueryParameter['data'] = data;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Signup
         * @param {string} loginUser 
         * @param {string} passwordUser 
         * @param {string} firstName 
         * @param {string} lastName 
         * @param {string} email 
         * @param {string} phoneNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpSignupPost: async (loginUser: string, passwordUser: string, firstName: string, lastName: string, email: string, phoneNumber: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginUser' is not null or undefined
            assertParamExists('signUpSignupPost', 'loginUser', loginUser)
            // verify required parameter 'passwordUser' is not null or undefined
            assertParamExists('signUpSignupPost', 'passwordUser', passwordUser)
            // verify required parameter 'firstName' is not null or undefined
            assertParamExists('signUpSignupPost', 'firstName', firstName)
            // verify required parameter 'lastName' is not null or undefined
            assertParamExists('signUpSignupPost', 'lastName', lastName)
            // verify required parameter 'email' is not null or undefined
            assertParamExists('signUpSignupPost', 'email', email)
            // verify required parameter 'phoneNumber' is not null or undefined
            assertParamExists('signUpSignupPost', 'phoneNumber', phoneNumber)
            const localVarPath = `/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (loginUser !== undefined) {
                localVarQueryParameter['loginUser'] = loginUser;
            }

            if (passwordUser !== undefined) {
                localVarQueryParameter['passwordUser'] = passwordUser;
            }

            if (firstName !== undefined) {
                localVarQueryParameter['firstName'] = firstName;
            }

            if (lastName !== undefined) {
                localVarQueryParameter['lastName'] = lastName;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (phoneNumber !== undefined) {
                localVarQueryParameter['phoneNumber'] = phoneNumber;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Addnewgame
         * @param {string} userToken 
         * @param {string} title 
         * @param {number} coordX 
         * @param {number} coordY 
         * @param {string} description 
         * @param {number} tag 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNewGameAddNewGamePost(userToken: string, title: string, coordX: number, coordY: number, description: string, tag: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNewGameAddNewGamePost(userToken, title, coordX, coordY, description, tag, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addNewGameAddNewGamePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Getcities
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCitiesGetCitiesPost(skip?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCitiesGetCitiesPost(skip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getCitiesGetCitiesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Getuser
         * @param {number} idUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserUserPost(idUser: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserUserPost(idUser, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUserUserPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Loginbytoken
         * @param {string} userToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logInByTokenLoginByTokenPost(userToken: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logInByTokenLoginByTokenPost(userToken, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.logInByTokenLoginByTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Login
         * @param {string} loginUser 
         * @param {string} passwordUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logInLoginPost(loginUser: string, passwordUser: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logInLoginPost(loginUser, passwordUser, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.logInLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Readmain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readMainGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readMainGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.readMainGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searchforgameauthor
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForGameAuthorSearchForGameAuthorPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForGameAuthorSearchForGameAuthorPost(data, sort, skip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchForGameAuthorSearchForGameAuthorPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searchforgamedate
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForGameDateSearchForGameDatePost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForGameDateSearchForGameDatePost(data, sort, skip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchForGameDateSearchForGameDatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searchforgamename
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForGameNameSearchForGameNamePost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForGameNameSearchForGameNamePost(data, sort, skip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchForGameNameSearchForGameNamePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searchforgame
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForGameSearchForGameCityPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForGameSearchForGameCityPost(data, sort, skip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchForGameSearchForGameCityPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searchforgametags
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForGameTagsSearchForGameTagsPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForGameTagsSearchForGameTagsPost(data, sort, skip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchForGameTagsSearchForGameTagsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Signup
         * @param {string} loginUser 
         * @param {string} passwordUser 
         * @param {string} firstName 
         * @param {string} lastName 
         * @param {string} email 
         * @param {string} phoneNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUpSignupPost(loginUser: string, passwordUser: string, firstName: string, lastName: string, email: string, phoneNumber: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUpSignupPost(loginUser, passwordUser, firstName, lastName, email, phoneNumber, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.signUpSignupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Addnewgame
         * @param {string} userToken 
         * @param {string} title 
         * @param {number} coordX 
         * @param {number} coordY 
         * @param {string} description 
         * @param {number} tag 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewGameAddNewGamePost(userToken: string, title: string, coordX: number, coordY: number, description: string, tag: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.addNewGameAddNewGamePost(userToken, title, coordX, coordY, description, tag, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Getcities
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCitiesGetCitiesPost(skip?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getCitiesGetCitiesPost(skip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Getuser
         * @param {number} idUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserUserPost(idUser: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getUserUserPost(idUser, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Loginbytoken
         * @param {string} userToken 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logInByTokenLoginByTokenPost(userToken: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.logInByTokenLoginByTokenPost(userToken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login
         * @param {string} loginUser 
         * @param {string} passwordUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logInLoginPost(loginUser: string, passwordUser: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.logInLoginPost(loginUser, passwordUser, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Readmain
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readMainGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.readMainGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searchforgameauthor
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameAuthorSearchForGameAuthorPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.searchForGameAuthorSearchForGameAuthorPost(data, sort, skip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searchforgamedate
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameDateSearchForGameDatePost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.searchForGameDateSearchForGameDatePost(data, sort, skip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searchforgamename
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameNameSearchForGameNamePost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.searchForGameNameSearchForGameNamePost(data, sort, skip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searchforgame
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameSearchForGameCityPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.searchForGameSearchForGameCityPost(data, sort, skip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searchforgametags
         * @param {string} data 
         * @param {string} [sort] 
         * @param {number} [skip] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForGameTagsSearchForGameTagsPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.searchForGameTagsSearchForGameTagsPost(data, sort, skip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Signup
         * @param {string} loginUser 
         * @param {string} passwordUser 
         * @param {string} firstName 
         * @param {string} lastName 
         * @param {string} email 
         * @param {string} phoneNumber 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpSignupPost(loginUser: string, passwordUser: string, firstName: string, lastName: string, email: string, phoneNumber: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.signUpSignupPost(loginUser, passwordUser, firstName, lastName, email, phoneNumber, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Addnewgame
     * @param {string} userToken 
     * @param {string} title 
     * @param {number} coordX 
     * @param {number} coordY 
     * @param {string} description 
     * @param {number} tag 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public addNewGameAddNewGamePost(userToken: string, title: string, coordX: number, coordY: number, description: string, tag: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addNewGameAddNewGamePost(userToken, title, coordX, coordY, description, tag, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Getcities
     * @param {number} [skip] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getCitiesGetCitiesPost(skip?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getCitiesGetCitiesPost(skip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Getuser
     * @param {number} idUser 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUserUserPost(idUser: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserUserPost(idUser, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Loginbytoken
     * @param {string} userToken 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public logInByTokenLoginByTokenPost(userToken: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logInByTokenLoginByTokenPost(userToken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login
     * @param {string} loginUser 
     * @param {string} passwordUser 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public logInLoginPost(loginUser: string, passwordUser: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logInLoginPost(loginUser, passwordUser, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Readmain
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readMainGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readMainGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searchforgameauthor
     * @param {string} data 
     * @param {string} [sort] 
     * @param {number} [skip] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchForGameAuthorSearchForGameAuthorPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchForGameAuthorSearchForGameAuthorPost(data, sort, skip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searchforgamedate
     * @param {string} data 
     * @param {string} [sort] 
     * @param {number} [skip] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchForGameDateSearchForGameDatePost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchForGameDateSearchForGameDatePost(data, sort, skip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searchforgamename
     * @param {string} data 
     * @param {string} [sort] 
     * @param {number} [skip] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchForGameNameSearchForGameNamePost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchForGameNameSearchForGameNamePost(data, sort, skip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searchforgame
     * @param {string} data 
     * @param {string} [sort] 
     * @param {number} [skip] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchForGameSearchForGameCityPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchForGameSearchForGameCityPost(data, sort, skip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searchforgametags
     * @param {string} data 
     * @param {string} [sort] 
     * @param {number} [skip] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchForGameTagsSearchForGameTagsPost(data: string, sort?: string, skip?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchForGameTagsSearchForGameTagsPost(data, sort, skip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Signup
     * @param {string} loginUser 
     * @param {string} passwordUser 
     * @param {string} firstName 
     * @param {string} lastName 
     * @param {string} email 
     * @param {string} phoneNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public signUpSignupPost(loginUser: string, passwordUser: string, firstName: string, lastName: string, email: string, phoneNumber: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).signUpSignupPost(loginUser, passwordUser, firstName, lastName, email, phoneNumber, options).then((request) => request(this.axios, this.basePath));
    }
}



